In [1]:
import pandas as pd
flights=pd.read_csv("data/flights.csv")
flights

C:\Users\Prince\AppData\Local\Temp\ipykernel_9604\3384812990.py:2: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  flights=pd.read_csv("data/flights.csv")

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015,12,31,4,B6,688,N657JB,LAX,BOS,2359,...,753.0,-26.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819075,2015,12,31,4,B6,745,N828JB,JFK,PSE,2359,...,430.0,-16.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819076,2015,12,31,4,B6,1503,N913JB,JFK,SJU,2359,...,432.0,-8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819077,2015,12,31,4,B6,333,N527JB,MCO,SJU,2359,...,330.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819078,2015,12,31,4,B6,839,N534JB,JFK,BQN,2359,...,442.0,2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
flights.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#shape of the dataset
flights.shape

(5819079, 31)

In [4]:
#taking info
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB

In [5]:
#taking and understanding each and every column 
flights['YEAR']
flights['YEAR'].head()

0    2015
1    2015
2    2015
3    2015
4    2015
Name: YEAR, dtype: int64

In [6]:
#understanding month and day
flights['MONTH'].head()

0    1
1    1
2    1
3    1
4    1
Name: MONTH, dtype: int64

In [7]:
flights['DAY'].head()
flights['DAY'].tail()

5819074    31
5819075    31
5819076    31
5819077    31
5819078    31
Name: DAY, dtype: int64

In [8]:
#taking info DAY OF WEEK
flights['DAY_OF_WEEK'].head()
flights['DAY_OF_WEEK'].tail()

5819074    4
5819075    4
5819076    4
5819077    4
5819078    4
Name: DAY_OF_WEEK, dtype: int64

In [9]:
import random
flights['DAY_OF_WEEK'].sample(10)
#just to see the random rows.

3407013    5
438673     4
1572453    6
3855027    4
1185291    3
4733324    4
5757566    1
844584     3
2663154    3
5236805    2
Name: DAY_OF_WEEK, dtype: int64

In [10]:
#taking AIRLINE column.
flights['AIRLINE']

0          AS
1          AA
2          US
3          AA
4          AS
           ..
5819074    B6
5819075    B6
5819076    B6
5819077    B6
5819078    B6
Name: AIRLINE, Length: 5819079, dtype: object

In [ ]:
#changing the airline column into th numeric 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

flights=pd.read_csv("data/flights.csv")
flights
encoder=OneHotEncoder(sparse_output=False,drop='first')
airline_encoded=encoder.fit_transform(flights[['AIRLINE']])
airline_df=pd.DataFrame(airline_encoded,columns=encoder.get_feature_names_out(['AIRLINE']))
flights = pd.concat(
    [flights.drop('AIRLINE', axis=1), airline_df],
    axis=1
)

flights

In [ ]:
flights.drop('TAIL_NUMBER', axis=1, inplace=True)
flights

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,...,AIRLINE_EV,AIRLINE_F9,AIRLINE_HA,AIRLINE_MQ,AIRLINE_NK,AIRLINE_OO,AIRLINE_UA,AIRLINE_US,AIRLINE_VX,AIRLINE_WN
0,2015,1,1,4,98,ANC,SEA,5,2354.0,-11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015,1,1,4,2336,LAX,PBI,10,2.0,-8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015,1,1,4,840,SFO,CLT,20,18.0,-2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2015,1,1,4,258,LAX,MIA,20,15.0,-5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015,1,1,4,135,SEA,ANC,25,24.0,-1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015,12,31,4,688,LAX,BOS,2359,2355.0,-4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5819075,2015,12,31,4,745,JFK,PSE,2359,2355.0,-4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5819076,2015,12,31,4,1503,JFK,SJU,2359,2350.0,-9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5819077,2015,12,31,4,333,MCO,SJU,2359,2353.0,-6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5819078,2015,12,31,4,839,JFK,BQN,2359,14.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
flights.duplicated().sum()
flights.drop_duplicates(inplace=True)

In [ ]:
#GETTING UNIQUE VALUES OF AIRPORT 
flights['ORIGIN_AIRPORT'].nunique()

930

In [ ]:
#TAKING TOP 10 AIRPORTS 
top_origins = flights['ORIGIN_AIRPORT'].value_counts().head(10).index
flights['ORIGIN_AIRPORT'] = flights['ORIGIN_AIRPORT'].apply(
    lambda x: x if x in top_origins else 'OTHER'
)
flights['ORIGIN_AIRPORT'].value_counts()

ORIGIN_AIRPORT
OTHER    3869337
ATL       346836
ORD       285884
DFW       239551
DEN       196055
LAX       194673
SFO       148008
PHX       146815
IAH       146622
LAS       133181
MSP       112117
Name: count, dtype: int64

In [ ]:
#APPLYING ONE HOT ENCODER TO ORIGIN_AIRPORT
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
encoded1=OneHotEncoder(sparse_output=False,drop='first')
origin_encoded=encoded1.fit_transform(flights[['ORIGIN_AIRPORT']])
origin_df=pd.DataFrame(origin_encoded,columns=encoded1.get_feature_names_out(['ORIGIN_AIRPORT']),index=flights.index)
flights = pd.concat(
    [flights.drop('ORIGIN_AIRPORT', axis=1), origin_df],
    axis=1)

flights

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,...,ORIGIN_AIRPORT_DEN,ORIGIN_AIRPORT_DFW,ORIGIN_AIRPORT_IAH,ORIGIN_AIRPORT_LAS,ORIGIN_AIRPORT_LAX,ORIGIN_AIRPORT_MSP,ORIGIN_AIRPORT_ORD,ORIGIN_AIRPORT_OTHER,ORIGIN_AIRPORT_PHX,ORIGIN_AIRPORT_SFO
0,2015,1,1,4,98,SEA,5,2354.0,-11.0,21.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2015,1,1,4,2336,PBI,10,2.0,-8.0,12.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,2015,1,1,4,840,CLT,20,18.0,-2.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2015,1,1,4,258,MIA,20,15.0,-5.0,15.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,2015,1,1,4,135,ANC,25,24.0,-1.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015,12,31,4,688,BOS,2359,2355.0,-4.0,22.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5819075,2015,12,31,4,745,PSE,2359,2355.0,-4.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819076,2015,12,31,4,1503,SJU,2359,2350.0,-9.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819077,2015,12,31,4,333,SJU,2359,2353.0,-6.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819078,2015,12,31,4,839,BQN,2359,14.0,15.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
#DESTINATION AIRPORT
flights['DESTINATION_AIRPORT'].nunique()

930

In [ ]:
top_destinations = flights['DESTINATION_AIRPORT'].value_counts().head(10).index
flights['DESTINATION_AIRPORT'] = flights['DESTINATION_AIRPORT'].apply(
    lambda x: x if x in top_destinations else 'OTHER'
)
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

encoder = OneHotEncoder(sparse_output=False, drop='first')

dest_encoded = encoder.fit_transform(flights[['DESTINATION_AIRPORT']])

dest_df = pd.DataFrame(
    dest_encoded,
    columns=encoder.get_feature_names_out(['DESTINATION_AIRPORT']),
    index=flights.index
)

flights = pd.concat(
    [flights.drop('DESTINATION_AIRPORT', axis=1), dest_df],
    axis=1
)

flights

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,DESTINATION_AIRPORT_DEN,DESTINATION_AIRPORT_DFW,DESTINATION_AIRPORT_IAH,DESTINATION_AIRPORT_LAS,DESTINATION_AIRPORT_LAX,DESTINATION_AIRPORT_MSP,DESTINATION_AIRPORT_ORD,DESTINATION_AIRPORT_OTHER,DESTINATION_AIRPORT_PHX,DESTINATION_AIRPORT_SFO
0,2015,1,1,4,98,5,2354.0,-11.0,21.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2015,1,1,4,2336,10,2.0,-8.0,12.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2015,1,1,4,840,20,18.0,-2.0,16.0,34.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2015,1,1,4,258,20,15.0,-5.0,15.0,30.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2015,1,1,4,135,25,24.0,-1.0,11.0,35.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015,12,31,4,688,2359,2355.0,-4.0,22.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819075,2015,12,31,4,745,2359,2355.0,-4.0,17.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819076,2015,12,31,4,1503,2359,2350.0,-9.0,17.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819077,2015,12,31,4,333,2359,2353.0,-6.0,10.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819078,2015,12,31,4,839,2359,14.0,15.0,14.0,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
flights.drop(
    [
        'ARRIVAL_DELAY',
        'LATE_AIRCRAFT_DELAY',
        'WEATHER_DELAY',
        'AIR_SYSTEM_DELAY',
        'SECURITY_DELAY'
    ],
    axis=1,
    inplace=True
)

In [ ]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 55 columns):
 #   Column                     Dtype
---  ------                     -----
 0   YEAR                       int64
 1   MONTH                      int64
 2   DAY                        int64
 3   DAY_OF_WEEK                int64
 4   FLIGHT_NUMBER              int64
 5   SCHEDULED_DEPARTURE        int64
 6   DEPARTURE_TIME             float64
 7   DEPARTURE_DELAY            float64
 8   TAXI_OUT                   float64
 9   WHEELS_OFF                 float64
 10  SCHEDULED_TIME             float64
 11  ELAPSED_TIME               float64
 12  AIR_TIME                   float64
 13  DISTANCE                   int64
 14  WHEELS_ON                  float64
 15  TAXI_IN                    float64
 16  SCHEDULED_ARRIVAL          int64
 17  ARRIVAL_TIME               float64
 18  DIVERTED                   int64
 19  CANCELLED                  int64
 20  CANCELLATION_REASON        object
 21  AIRLINE_DELAY              float64
 22  AIRLINE_AS                 float64
 23  AIRLINE_B6                 float64
 24  AIRLINE_DL                 float64
 25  AIRLINE_EV                 float64
 26  AIRLINE_F9                 float64
 27  AIRLINE_HA                 float64
 28  AIRLINE_MQ                 float64
 29  AIRLINE_NK                 float64
 30  AIRLINE_OO                 float64
 31  AIRLINE_UA                 float64
 32  AIRLINE_US                 float64
 33  AIRLINE_VX                 float64
 34  AIRLINE_WN                 float64
 35  ORIGIN_AIRPORT_DEN         float64
 36  ORIGIN_AIRPORT_DFW         float64
 37  ORIGIN_AIRPORT_IAH         float64
 38  ORIGIN_AIRPORT_LAS         float64
 39  ORIGIN_AIRPORT_LAX         float64
 40  ORIGIN_AIRPORT_MSP         float64
 41  ORIGIN_AIRPORT_ORD         float64
 42  ORIGIN_AIRPORT_OTHER       float64
 43  ORIGIN_AIRPORT_PHX         float64
 44  ORIGIN_AIRPORT_SFO         float64
 45  DESTINATION_AIRPORT_DEN    float64
 46  DESTINATION_AIRPORT_DFW    float64
 47  DESTINATION_AIRPORT_IAH    float64
 48  DESTINATION_AIRPORT_LAS    float64
 49  DESTINATION_AIRPORT_LAX    float64
 50  DESTINATION_AIRPORT_MSP    float64
 51  DESTINATION_AIRPORT_ORD    float64
 52  DESTINATION_AIRPORT_OTHER  float64
 53  DESTINATION_AIRPORT_PHX    float64
 54  DESTINATION_AIRPORT_SFO    float64
dtypes: float64(44), int64(10), object(1)
memory usage: 2.4+ GB

In [ ]:
flights.isnull().sum()

YEAR                               0
MONTH                              0
DAY                                0
DAY_OF_WEEK                        0
FLIGHT_NUMBER                      0
SCHEDULED_DEPARTURE                0
DEPARTURE_TIME                 86153
DEPARTURE_DELAY                86153
TAXI_OUT                       89047
WHEELS_OFF                     89047
SCHEDULED_TIME                     6
ELAPSED_TIME                  105071
AIR_TIME                      105071
DISTANCE                           0
WHEELS_ON                      92513
TAXI_IN                        92513
SCHEDULED_ARRIVAL                  0
ARRIVAL_TIME                   92513
DIVERTED                           0
CANCELLED                          0
CANCELLATION_REASON          5729195
AIRLINE_DELAY                4755640
AIRLINE_AS                         0
AIRLINE_B6                         0
AIRLINE_DL                         0
AIRLINE_EV                         0
AIRLINE_F9                         0
AIRLINE_HA                         0
AIRLINE_MQ                         0
AIRLINE_NK                         0
AIRLINE_OO                         0
AIRLINE_UA                         0
AIRLINE_US                         0
AIRLINE_VX                         0
AIRLINE_WN                         0
ORIGIN_AIRPORT_DEN                 0
ORIGIN_AIRPORT_DFW                 0
ORIGIN_AIRPORT_IAH                 0
ORIGIN_AIRPORT_LAS                 0
ORIGIN_AIRPORT_LAX                 0
ORIGIN_AIRPORT_MSP                 0
ORIGIN_AIRPORT_ORD                 0
ORIGIN_AIRPORT_OTHER               0
ORIGIN_AIRPORT_PHX                 0
ORIGIN_AIRPORT_SFO                 0
DESTINATION_AIRPORT_DEN            0
DESTINATION_AIRPORT_DFW            0
DESTINATION_AIRPORT_IAH            0
DESTINATION_AIRPORT_LAS            0
DESTINATION_AIRPORT_LAX            0
DESTINATION_AIRPORT_MSP            0
DESTINATION_AIRPORT_ORD            0
DESTINATION_AIRPORT_OTHER          0
DESTINATION_AIRPORT_PHX            0
DESTINATION_AIRPORT_SFO            0
dtype: int64

In [ ]:
flights.drop('CANCELLATION_REASON', axis=1, inplace=True)
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 54 columns):
 #   Column                     Dtype
---  ------                     -----
 0   YEAR                       int64
 1   MONTH                      int64
 2   DAY                        int64
 3   DAY_OF_WEEK                int64
 4   FLIGHT_NUMBER              int64
 5   SCHEDULED_DEPARTURE        int64
 6   DEPARTURE_TIME             float64
 7   DEPARTURE_DELAY            float64
 8   TAXI_OUT                   float64
 9   WHEELS_OFF                 float64
 10  SCHEDULED_TIME             float64
 11  ELAPSED_TIME               float64
 12  AIR_TIME                   float64
 13  DISTANCE                   int64
 14  WHEELS_ON                  float64
 15  TAXI_IN                    float64
 16  SCHEDULED_ARRIVAL          int64
 17  ARRIVAL_TIME               float64
 18  DIVERTED                   int64
 19  CANCELLED                  int64
 20  AIRLINE_DELAY              float64
 21  AIRLINE_AS                 float64
 22  AIRLINE_B6                 float64
 23  AIRLINE_DL                 float64
 24  AIRLINE_EV                 float64
 25  AIRLINE_F9                 float64
 26  AIRLINE_HA                 float64
 27  AIRLINE_MQ                 float64
 28  AIRLINE_NK                 float64
 29  AIRLINE_OO                 float64
 30  AIRLINE_UA                 float64
 31  AIRLINE_US                 float64
 32  AIRLINE_VX                 float64
 33  AIRLINE_WN                 float64
 34  ORIGIN_AIRPORT_DEN         float64
 35  ORIGIN_AIRPORT_DFW         float64
 36  ORIGIN_AIRPORT_IAH         float64
 37  ORIGIN_AIRPORT_LAS         float64
 38  ORIGIN_AIRPORT_LAX         float64
 39  ORIGIN_AIRPORT_MSP         float64
 40  ORIGIN_AIRPORT_ORD         float64
 41  ORIGIN_AIRPORT_OTHER       float64
 42  ORIGIN_AIRPORT_PHX         float64
 43  ORIGIN_AIRPORT_SFO         float64
 44  DESTINATION_AIRPORT_DEN    float64
 45  DESTINATION_AIRPORT_DFW    float64
 46  DESTINATION_AIRPORT_IAH    float64
 47  DESTINATION_AIRPORT_LAS    float64
 48  DESTINATION_AIRPORT_LAX    float64
 49  DESTINATION_AIRPORT_MSP    float64
 50  DESTINATION_AIRPORT_ORD    float64
 51  DESTINATION_AIRPORT_OTHER  float64
 52  DESTINATION_AIRPORT_PHX    float64
 53  DESTINATION_AIRPORT_SFO    float64
dtypes: float64(44), int64(10)
memory usage: 2.3 GB

In [ ]:
flights['CANCELLED'].tail()

5819074    0
5819075    0
5819076    0
5819077    0
5819078    0
Name: CANCELLED, dtype: int64

In [ ]:
flights=flights[flights['CANCELLED']==0]
flights

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,DESTINATION_AIRPORT_DEN,DESTINATION_AIRPORT_DFW,DESTINATION_AIRPORT_IAH,DESTINATION_AIRPORT_LAS,DESTINATION_AIRPORT_LAX,DESTINATION_AIRPORT_MSP,DESTINATION_AIRPORT_ORD,DESTINATION_AIRPORT_OTHER,DESTINATION_AIRPORT_PHX,DESTINATION_AIRPORT_SFO
0,2015,1,1,4,98,5,2354.0,-11.0,21.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2015,1,1,4,2336,10,2.0,-8.0,12.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2015,1,1,4,840,20,18.0,-2.0,16.0,34.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2015,1,1,4,258,20,15.0,-5.0,15.0,30.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2015,1,1,4,135,25,24.0,-1.0,11.0,35.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015,12,31,4,688,2359,2355.0,-4.0,22.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819075,2015,12,31,4,745,2359,2355.0,-4.0,17.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819076,2015,12,31,4,1503,2359,2350.0,-9.0,17.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819077,2015,12,31,4,333,2359,2353.0,-6.0,10.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5819078,2015,12,31,4,839,2359,14.0,15.0,14.0,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
flights.isnull().sum()

YEAR                               0
MONTH                              0
DAY                                0
DAY_OF_WEEK                        0
FLIGHT_NUMBER                      0
SCHEDULED_DEPARTURE                0
DEPARTURE_TIME                     0
DEPARTURE_DELAY                    0
TAXI_OUT                           0
WHEELS_OFF                         0
SCHEDULED_TIME                     1
ELAPSED_TIME                   15187
AIR_TIME                       15187
DISTANCE                           0
WHEELS_ON                       2629
TAXI_IN                         2629
SCHEDULED_ARRIVAL                  0
ARRIVAL_TIME                    2629
DIVERTED                           0
CANCELLED                          0
AIRLINE_DELAY                4665756
AIRLINE_AS                         0
AIRLINE_B6                         0
AIRLINE_DL                         0
AIRLINE_EV                         0
AIRLINE_F9                         0
AIRLINE_HA                         0
AIRLINE_MQ                         0
AIRLINE_NK                         0
AIRLINE_OO                         0
AIRLINE_UA                         0
AIRLINE_US                         0
AIRLINE_VX                         0
AIRLINE_WN                         0
ORIGIN_AIRPORT_DEN                 0
ORIGIN_AIRPORT_DFW                 0
ORIGIN_AIRPORT_IAH                 0
ORIGIN_AIRPORT_LAS                 0
ORIGIN_AIRPORT_LAX                 0
ORIGIN_AIRPORT_MSP                 0
ORIGIN_AIRPORT_ORD                 0
ORIGIN_AIRPORT_OTHER               0
ORIGIN_AIRPORT_PHX                 0
ORIGIN_AIRPORT_SFO                 0
DESTINATION_AIRPORT_DEN            0
DESTINATION_AIRPORT_DFW            0
DESTINATION_AIRPORT_IAH            0
DESTINATION_AIRPORT_LAS            0
DESTINATION_AIRPORT_LAX            0
DESTINATION_AIRPORT_MSP            0
DESTINATION_AIRPORT_ORD            0
DESTINATION_AIRPORT_OTHER          0
DESTINATION_AIRPORT_PHX            0
DESTINATION_AIRPORT_SFO            0
dtype: int64

In [ ]:
flights.drop('AIRLINE_DELAY', axis=1, inplace=True,errors='ignore')

C:\Users\Prince\AppData\Local\Temp\ipykernel_17264\2580072637.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flights.drop('AIRLINE_DELAY', axis=1, inplace=True,errors='ignore')

In [ ]:
'AIRLINE_DELAY' in flights.columns

False

In [ ]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5729195 entries, 0 to 5819078
Data columns (total 53 columns):
 #   Column                     Dtype
---  ------                     -----
 0   YEAR                       int64
 1   MONTH                      int64
 2   DAY                        int64
 3   DAY_OF_WEEK                int64
 4   FLIGHT_NUMBER              int64
 5   SCHEDULED_DEPARTURE        int64
 6   DEPARTURE_TIME             float64
 7   DEPARTURE_DELAY            float64
 8   TAXI_OUT                   float64
 9   WHEELS_OFF                 float64
 10  SCHEDULED_TIME             float64
 11  ELAPSED_TIME               float64
 12  AIR_TIME                   float64
 13  DISTANCE                   int64
 14  WHEELS_ON                  float64
 15  TAXI_IN                    float64
 16  SCHEDULED_ARRIVAL          int64
 17  ARRIVAL_TIME               float64
 18  DIVERTED                   int64
 19  CANCELLED                  int64
 20  AIRLINE_AS                 float64
 21  AIRLINE_B6                 float64
 22  AIRLINE_DL                 float64
 23  AIRLINE_EV                 float64
 24  AIRLINE_F9                 float64
 25  AIRLINE_HA                 float64
 26  AIRLINE_MQ                 float64
 27  AIRLINE_NK                 float64
 28  AIRLINE_OO                 float64
 29  AIRLINE_UA                 float64
 30  AIRLINE_US                 float64
 31  AIRLINE_VX                 float64
 32  AIRLINE_WN                 float64
 33  ORIGIN_AIRPORT_DEN         float64
 34  ORIGIN_AIRPORT_DFW         float64
 35  ORIGIN_AIRPORT_IAH         float64
 36  ORIGIN_AIRPORT_LAS         float64
 37  ORIGIN_AIRPORT_LAX         float64
 38  ORIGIN_AIRPORT_MSP         float64
 39  ORIGIN_AIRPORT_ORD         float64
 40  ORIGIN_AIRPORT_OTHER       float64
 41  ORIGIN_AIRPORT_PHX         float64
 42  ORIGIN_AIRPORT_SFO         float64
 43  DESTINATION_AIRPORT_DEN    float64
 44  DESTINATION_AIRPORT_DFW    float64
 45  DESTINATION_AIRPORT_IAH    float64
 46  DESTINATION_AIRPORT_LAS    float64
 47  DESTINATION_AIRPORT_LAX    float64
 48  DESTINATION_AIRPORT_MSP    float64
 49  DESTINATION_AIRPORT_ORD    float64
 50  DESTINATION_AIRPORT_OTHER  float64
 51  DESTINATION_AIRPORT_PHX    float64
 52  DESTINATION_AIRPORT_SFO    float64
dtypes: float64(43), int64(10)
memory usage: 2.3 GB

In [ ]:
flights.isnull().sum()

YEAR                             0
MONTH                            0
DAY                              0
DAY_OF_WEEK                      0
FLIGHT_NUMBER                    0
SCHEDULED_DEPARTURE              0
DEPARTURE_TIME                   0
DEPARTURE_DELAY                  0
TAXI_OUT                         0
WHEELS_OFF                       0
SCHEDULED_TIME                   1
ELAPSED_TIME                 15187
AIR_TIME                     15187
DISTANCE                         0
WHEELS_ON                     2629
TAXI_IN                       2629
SCHEDULED_ARRIVAL                0
ARRIVAL_TIME                  2629
DIVERTED                         0
CANCELLED                        0
AIRLINE_AS                       0
AIRLINE_B6                       0
AIRLINE_DL                       0
AIRLINE_EV                       0
AIRLINE_F9                       0
AIRLINE_HA                       0
AIRLINE_MQ                       0
AIRLINE_NK                       0
AIRLINE_OO                       0
AIRLINE_UA                       0
AIRLINE_US                       0
AIRLINE_VX                       0
AIRLINE_WN                       0
ORIGIN_AIRPORT_DEN               0
ORIGIN_AIRPORT_DFW               0
ORIGIN_AIRPORT_IAH               0
ORIGIN_AIRPORT_LAS               0
ORIGIN_AIRPORT_LAX               0
ORIGIN_AIRPORT_MSP               0
ORIGIN_AIRPORT_ORD               0
ORIGIN_AIRPORT_OTHER             0
ORIGIN_AIRPORT_PHX               0
ORIGIN_AIRPORT_SFO               0
DESTINATION_AIRPORT_DEN          0
DESTINATION_AIRPORT_DFW          0
DESTINATION_AIRPORT_IAH          0
DESTINATION_AIRPORT_LAS          0
DESTINATION_AIRPORT_LAX          0
DESTINATION_AIRPORT_MSP          0
DESTINATION_AIRPORT_ORD          0
DESTINATION_AIRPORT_OTHER        0
DESTINATION_AIRPORT_PHX          0
DESTINATION_AIRPORT_SFO          0
dtype: int64

In [ ]:
flights['SCHEDULED_TIME'].fillna(
    flights['SCHEDULED_TIME'].median(),
    inplace=True
)

C:\Users\Prince\AppData\Local\Temp\ipykernel_17264\1446334432.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  flights['SCHEDULED_TIME'].fillna(
C:\Users\Prince\AppData\Local\Temp\ipykernel_17264\1446334432.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flights['SCHEDULED_TIME'].fillna(

In [ ]:
flights.dropna(inplace=True)

C:\Users\Prince\AppData\Local\Temp\ipykernel_17264\3155674978.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flights.dropna(inplace=True)

In [ ]:
flights.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
FLIGHT_NUMBER                0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME               0
DEPARTURE_DELAY              0
TAXI_OUT                     0
WHEELS_OFF                   0
SCHEDULED_TIME               0
ELAPSED_TIME                 0
AIR_TIME                     0
DISTANCE                     0
WHEELS_ON                    0
TAXI_IN                      0
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME                 0
DIVERTED                     0
CANCELLED                    0
AIRLINE_AS                   0
AIRLINE_B6                   0
AIRLINE_DL                   0
AIRLINE_EV                   0
AIRLINE_F9                   0
AIRLINE_HA                   0
AIRLINE_MQ                   0
AIRLINE_NK                   0
AIRLINE_OO                   0
AIRLINE_UA                   0
AIRLINE_US                   0
AIRLINE_VX                   0
AIRLINE_WN                   0
ORIGIN_AIRPORT_DEN           0
ORIGIN_AIRPORT_DFW           0
ORIGIN_AIRPORT_IAH           0
ORIGIN_AIRPORT_LAS           0
ORIGIN_AIRPORT_LAX           0
ORIGIN_AIRPORT_MSP           0
ORIGIN_AIRPORT_ORD           0
ORIGIN_AIRPORT_OTHER         0
ORIGIN_AIRPORT_PHX           0
ORIGIN_AIRPORT_SFO           0
DESTINATION_AIRPORT_DEN      0
DESTINATION_AIRPORT_DFW      0
DESTINATION_AIRPORT_IAH      0
DESTINATION_AIRPORT_LAS      0
DESTINATION_AIRPORT_LAX      0
DESTINATION_AIRPORT_MSP      0
DESTINATION_AIRPORT_ORD      0
DESTINATION_AIRPORT_OTHER    0
DESTINATION_AIRPORT_PHX      0
DESTINATION_AIRPORT_SFO      0
dtype: int64

In [ ]:
#getting the target cloumns delayed.
flights['DELAYED']=flights['DEPARTURE_DELAY'].apply(lambda x:1 if x>0 else 0)
flights[['DELAYED','DEPARTURE_DELAY']].head()
flights[['DELAYED','DEPARTURE_DELAY']].tail()

C:\Users\Prince\AppData\Local\Temp\ipykernel_17264\2787371117.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flights['DELAYED']=flights['DEPARTURE_DELAY'].apply(lambda x:1 if x>0 else 0)

         DELAYED  DEPARTURE_DELAY
5819074        0             -4.0
5819075        0             -4.0
5819076        0             -9.0
5819077        0             -6.0
5819078        1             15.0

In [ ]:
#making my data short.
flights_sample=flights.sample(100000,random_state=42)
flights_sample

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,DESTINATION_AIRPORT_DFW,DESTINATION_AIRPORT_IAH,DESTINATION_AIRPORT_LAS,DESTINATION_AIRPORT_LAX,DESTINATION_AIRPORT_MSP,DESTINATION_AIRPORT_ORD,DESTINATION_AIRPORT_OTHER,DESTINATION_AIRPORT_PHX,DESTINATION_AIRPORT_SFO,DELAYED
3335058,2015,7,27,1,4553,1623,1629.0,6.0,12.0,1641.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
4857110,2015,10,30,5,1615,1823,1824.0,1.0,13.0,1837.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
4454180,2015,10,5,1,159,1150,1158.0,8.0,7.0,1205.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
5132772,2015,11,17,2,1265,1305,1305.0,0.0,9.0,1314.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
4075015,2015,9,11,5,4740,600,554.0,-6.0,19.0,613.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1030627,2015,3,9,1,525,900,859.0,-1.0,19.0,918.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4612825,2015,10,15,4,7369,1025,1015.0,-10.0,13.0,1028.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
1231578,2015,3,21,6,4514,1216,1210.0,-6.0,20.0,1230.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
2549035,2015,6,10,3,6353,1752,1752.0,0.0,14.0,1806.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1586578,2015,4,12,7,2135,1200,1157.0,-3.0,22.0,1219.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0

In [ ]:
#taking x and y
x=flights_sample.drop(columns=['DELAYED','DEPARTURE_DELAY'])
y=flights_sample['DELAYED']

In [ ]:
#training and testing 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
    x,y,
    test_size=0.2,
    random_state=42
)

In [ ]:
#setting up Logistic Regression 
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(
    max_iter=200,
    solver='saga',
    n_jobs=-1
)

In [ ]:
#now training model
model.fit(x_train,y_train)

C:\Users\Prince\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
C:\Users\Prince\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

LogisticRegression(max_iter=200, n_jobs=-1, solver='saga')

In [ ]:
#now prediction
y_pred=model.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 0, 0], shape=(20000,))

In [ ]:
#checking the accuracy store
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7564

In [ ]:
#checking for confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[12392,   263],
       [ 4609,  2736]])

In [ ]:
import joblib
joblib.dump(model, "flight_delay_model.pkl")

['flight_delay_model.pkl']

In [ ]:
import joblib
joblib.dump(x.columns.tolist(),"feature_columns.pkl")

['feature_columns.pkl']

In [ ]:
import sklearn
print(sklearn.__version__)

1.8.0